name: 🐛 Bug Report
description: Report a bug to help us improve
title: "[BUG] "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! 🙏

  - type: input
    id: version
    attributes:
      label: Version
      description: What version of the Driver Fatigue Detection System are you using?
      placeholder: e.g., v1.0.0 or commit hash if from source
    validations:
      required: true

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What operating system are you using?
      options:
        - Windows 10
        - Windows 11
        - macOS 10.15+
        - Ubuntu 18.04+
        - Ubuntu 20.04+
        - Ubuntu 22.04+
        - Other Linux distribution
        - Other (please specify in description)
    validations:
      required: true

  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug here...
    validations:
      required: true

  - type: textarea
    id: reproduction-steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should happen?
    validations:
      required: true

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: Drag and drop screenshots here

  - type: textarea
    id: logs
    attributes:
      label: Log Output
      description: If applicable, add relevant log output (check data/logs/ folder)
      placeholder: Paste log content here...

  - type: textarea
    id: hardware-info
    attributes:
      label: Hardware Information
      description: Information about your hardware setup
      placeholder: |
        - CPU: 
        - RAM: 
        - Camera: 
        - GPU (if applicable):

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
